"""
Encryption utility for sensitive data (bank account, IFSC, UPI).
Uses Fernet symmetric encryption. Store key securely in production.

This module now handles the case where the `cryptography` package is not
installed by raising clear runtime errors when encryption/decryption is
attempted. This avoids raising ModuleNotFoundError at import time.
"""
import os
import logging
from typing import Optional

# Attempt to import Fernet; if unavailable, provide informative errors only at call time
try:
    from cryptography.fernet import Fernet
    _HAS_CRYPTO = True
except Exception:
    Fernet = None  # type: ignore
    _HAS_CRYPTO = False
    logging.warning(
        "cryptography package not available. Encryption functions will raise an informative error. "
        "Install it with: pip install cryptography"
    )

# Key management: prefer environment variable; only generate a key if cryptography is available
FERNET_KEY = os.environ.get('MANGO_MARKET_ENCRYPTION_KEY')

# When running locally we persist a generated key to `instance/fernet.key` so
# encrypted values remain decryptable across process restarts. In production you
# should set `MANGO_MARKET_ENCRYPTION_KEY` to a stable value and keep it secret.
if _HAS_CRYPTO:
    # Helper: determine a path under the project `instance/` directory
    try:
        _base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
        _instance_key_path = os.path.join(_base_dir, 'instance', 'fernet.key')
    except Exception:
        _instance_key_path = None

    # Prefer env var when provided (explicit production configuration)
    if FERNET_KEY:
        key_bytes = FERNET_KEY.encode() if isinstance(FERNET_KEY, str) else FERNET_KEY
    else:
        # Try to load/create a persistent key file in instance/fernet.key
        key_bytes = None
        if _instance_key_path:
            try:
                os.makedirs(os.path.dirname(_instance_key_path), exist_ok=True)
                if os.path.exists(_instance_key_path):
                    with open(_instance_key_path, 'rb') as _f:
                        key_bytes = _f.read().strip() or None
                if key_bytes is None:
                    key_bytes = Fernet.generate_key()
                    with open(_instance_key_path, 'wb') as _f:
                        _f.write(key_bytes)
            except Exception:
                # If file persistence fails for any reason, fall back to an in-memory key
                key_bytes = Fernet.generate_key()
        else:
            key_bytes = Fernet.generate_key()

    fernet = Fernet(key_bytes)


def _missing_crypto_error():
    raise RuntimeError(
        "The 'cryptography' package is required for encryption/decryption. "
        "Install it in your virtual environment with: pip install cryptography"
    )


def encrypt_value(value: Optional[str]) -> Optional[str]:
    """Encrypt a string value and return the token (base64 str).

    Raises RuntimeError with installation instructions if cryptography isn't available.
    """
    if value is None:
        return None
    if not _HAS_CRYPTO:
        _missing_crypto_error()
    return fernet.encrypt(value.encode()).decode()


class DecryptionError(Exception):
    """Raised when a value appears to be encrypted but cannot be decrypted."""


def decrypt_value(token: Optional[str]) -> Optional[str]:
    """Decrypt a token produced by `encrypt_value` and return the original string.

    Behavior:
    - Returns None for `None` or empty/whitespace-only input.
    - If the value looks like a Fernet token (starts with 'gAAAAA') it will be
      decrypted. If decryption fails (e.g. wrong key / invalid token) a
      `DecryptionError` is raised so callers can return a proper error response.
    - If the value does not look like a Fernet token we assume it's plaintext
      (legacy data) and return it unchanged.

    Raises RuntimeError with installation instructions if cryptography isn't available.
    """
    if token is None:
        return None
    # Treat empty or whitespace-only tokens as absent
    if isinstance(token, str) and token.strip() == "":
        return None
    if not _HAS_CRYPTO:
        _missing_crypto_error()

    # Heuristic: Fernet tokens generated by cryptography.fernet typically start
    # with the literal prefix 'gAAAAA'. If the value doesn't look like a Fernet
    # token, assume it's legacy plaintext and return as-is.
    if not isinstance(token, str) or not token.startswith('gAAAAA'):
        return token

    # Token looks encrypted; attempt decryption and surface failures explicitly
    try:
        return fernet.decrypt(token.encode()).decode()
    except Exception as e:
        try:
            from cryptography.fernet import InvalidToken
        except Exception:
            InvalidToken = None  # type: ignore

        if InvalidToken is not None and isinstance(e, InvalidToken):
            logging.exception("Invalid Fernet token or decryption failed")
            raise DecryptionError("Failed to decrypt value: invalid token or wrong key") from e

        logging.exception("Unexpected error during decryption")
        raise DecryptionError("Failed to decrypt value due to unexpected error") from e


def safe_decrypt(token: Optional[str]) -> Optional[str]:
    """Safe wrapper around `decrypt_value`.

    - Returns None when the input is None/empty.
    - Catches decryption-related errors and runtime errors (e.g. missing
      cryptography package) and returns None instead of raising so callers
      can continue and return a meaningful JSON error if needed.
    - Logs the exception for diagnostics.
    """
    try:
        return decrypt_value(token)
    except DecryptionError as de:
        logging.exception("Decryption failed: %s", str(de))
        return None
    except RuntimeError as re:
        # Missing cryptography or other runtime failure
        logging.exception("Runtime error during decryption: %s", str(re))
        return None
    except Exception as e:
        logging.exception("Unexpected error during safe_decrypt: %s", str(e))
        return None
